- _includes/grupopv/body/footer/top.html
Fixes https://github.com/cetinajero/denac.mx/issues/9
> Modify google form for comments and complaints

- _includes/components/product-cards/progressive.html
- _sass/components/product-cards/_progressive.scss
- assets/css/main.scss
> Add promotional prices to progressive product-card component

- _includes/components/nav-tabs/product-nav-tab.html
- _includes/components/product-cards/product-details.html
> Create product details component

- _includes/components/footers/progressive/custom-item.html
- _includes/components/footers/progressive/custom-title.html
- _includes/components/footers/progressive/footer.html
- _includes/components/footers/progressive/top.html
> Move footer data out of theme

- _includes/components/forms/google-forms.html
- _sass/components/forms/_google-forms.scss
> Add a progress bar to the google-forms component

- _includes/components/sliders/revolution-slider.html
Add an option to configure which sliders to display @ config.yml file
Also fix the missing dummy.png's `alt` errors reported by CI (HTML Proofer)
> Display sliders based on global config options

- _includes/components/product-cards/progressive.html
Fixes error at https://circleci.com/gh/cetinajero/grupopv.mx/22
> Set a default alt on img tag

- .gitattributes
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
- Rakefile
Also:
- Humanize rake tasks's alias
- Bump year
- Update dependabot link
- Add empty `.gitattributes`
- Add gems needed on windows
- Update radios rake task
> Add default options and rake options to `rake test:html`

- Rakefile
- _includes/body/header/search-bar.html
- _includes/body/header/search-contact-phone-buttons.html
- _includes/components/contact-cards/phone-directory.html
- _includes/components/login/progressive.html
- _includes/components/navbars/progressive.html
- _includes/components/scroll-to-tops/progressive.html
> Not allow hash href by default on CI tests

- _includes/components/megamenu/progressive.html
- _includes/components/nav-items/bootstrap.html
- _includes/components/nav-tabs/product-nav-tab.html
- _layouts/grid.html
- _layouts/product.html
> Add more customization per customers website

- _includes/components/maps/google-maps.html
- _includes/components/maps/google-maps.js
- _sass/components/maps/google-maps.scss
- assets/css/main.min.scss
Find our customers in all the 🌎! 🎉
> Create Google Maps component

- _includes/components/jumbotron/bootstrap.html
- _sass/components/jumbotron/bootstrap.scss
- assets/css/main.min.scss
Create Jumbotron component based on bootstrap 4
> Create Jumbotron component

- _includes/components/videos/background.html
- _sass/components/videos/background.scss
- assets/css/main.min.scss
> Create video background component

- _includes/components/info-cards/progressive.html
- _includes/components/jumbotron/bootstrap.html
> Create info card component

- _includes/components/maps/google-maps.js
Remove markers at lat: 0 / lng: 0 from google-maps component
🗺
> Remove markers from google-maps component

- _includes/components/maps/google-maps.js
> Display all branches from customers in google maps

- _includes/components/maps/google-maps.js
This allow us to configure the google maps component from the website
> Google maps config as variables

- _includes/components/timelines/9.html
- _sass/components/timelines/9.scss
- assets/css/main.min.scss
> Create timeline 9 component

- _includes/components/topbars/progressive.html
This will fix the CI errors found at https://circleci.com/gh/cetinajero/grupopv.mx/203
> Create login link button dynamically

- _includes/components/maps/google-maps.js
🗺  Added CSAPV to google maps component
> Add CSAPV customers to map and filter with query params

- _includes/components/maps/google-maps.js
The google-maps's markers and info windows are now customizable from our website 
🗺
> Make markers and infowindows customisable

- _includes/components/copyrights/progressive.html
- _includes/components/footers/progressive/footer.html
- _includes/components/footers/progressive/top.html
- _includes/components/social-media/progressive.html
> Refresh footer component

- _includes/components/modals/bootstrap.html
- _includes/components/modals/bootstrap.js
- _includes/components/spinners/bootstrap.html
- assets/vendors/themeforest/progressive/css/style.css
Also delete some CSS code from themeforest stylesheet
> Create spinner and modal components

- _includes/components/jumbotron/bootstrap.html
- _sass/components/jumbotron/bootstrap.scss
> Make the bootstrap jumbotron component more customizable

- _includes/components/generators/pdf/special-offers.html
> Enable CORS on pdf generator

- _includes/components/logos/progressive.html
> Migrate logos to S3

- _includes/components/lang-switchers/two-langs.html
- _sass/components/lang-switchers/_toogle-lang.scss
> Align lang switcher

- _includes/components/info-cards/search-results.html
- _includes/components/search-engines/lunr.html
- _includes/components/search-engines/lunr.js
- _sass/components/info-cards/search-results.scss
- assets/css/main.min.scss
> Create search engine component

- _includes/components/exchange-rates/progressive.html
- _includes/components/icons/bootstrap.html
- _includes/components/icons/progressive.html
- _includes/components/icons/progressive.js
- _includes/components/info-cards/search-results.html
- _includes/components/search-engines/lunr.html
- _includes/components/search-engines/lunr.js
- _includes/components/searchbars/progressive.html
- _includes/components/topbars/progressive.html
- _sass/components/logos/progressive.scss
- _sass/components/searchbars/progressive.scss
- assets/css/main.min.scss
- assets/vendors/themeforest/progressive/css/style.css
> Add 🔍 to navbar

- _includes/components/topbars/progressive.html
> Rearrange topbar elements

- _includes/components/logos/progressive.html
> Make logos component configurable

- _includes/components/sliders/bootstrap.html
- _sass/components/megamenu/progressive.scss
- _sass/components/product-cards/featured-product.scss
- Delete border en product-cards
- Delete font-size in media-brakpoint
> Carousel bootstrap

- _includes/components/firebase/sdk.html
- _layouts/default.html
> Added csapvApp to customers websites

- _includes/components/maps/image-map.html
More at: https://circleci.com/gh/cetinajero/grupopv.mx/385
✌️
> Add alt attribute to fix CI issue

- _includes/components/info-cards/search-results.html
- _includes/components/search-engines/lunr.html
- _includes/components/search-engines/lunr.js
> Add images to search results

- _includes/components/info-cards/search-results.html
Fixes issue on mobile view 🐛 
✌️
> Add text-break to search results URL

- _includes/components/copyrights/progressive.html
Requested by 04 thru a phone call
✌️
> Delete copyrights legend from footer

- _sass/layouts/_default.scss
- assets/css/main.min.scss
> Migrate background to AWS S3

- .gitignore
- package.json
- yarn.lock
> Fix Yarn's bootstrap warning

- assets/css/main.min.scss
- assets/node_modules/flag-icon-css/sass/_variables.scss
> Move flag-icon-css SASS variable to main.min.scss

- .gitignore
- _includes/components/filters/isotope.html
- _includes/components/filters/isotope.js
- _includes/components/info-cards/progressive.html
- _includes/components/product-cards/product-details.html
- _includes/components/product-cards/progressive.html
- _includes/components/search-engines/lunr.html
- _includes/components/searchbars/progressive.html
- _includes/components/topbars/progressive.html
- _includes/components/videos/background.html
- _layouts/grid.html
- _sass/components/product-cards/_product-details.scss
- assets/css/main.min.scss
- assets/node_modules/bootstrap/scss/_buttons.scss
- assets/node_modules/bootstrap/scss/mixins/_background-variant.scss
- assets/node_modules/bootstrap/scss/mixins/_box-shadow.scss
- assets/node_modules/bootstrap/scss/mixins/_buttons.scss
- assets/node_modules/bootstrap/scss/mixins/_gradients.scss
- assets/node_modules/bootstrap/scss/utilities/_background.scss
- assets/vendors/themeforest/progressive/css/style.css
This PR adds combination `filters` with `functions` to the `grid` layout using the [Isotope](https://isotope.metafizzy.co) library.
This PR also includes the migration to more Bootstrap SASS `partials` & `mixins` and there were _cleaned_ around _1000_ `CSS` lines.
✌️
> Add filters to grid layout 🎉 

- _includes/components/filters/isotope.html
> Fix issue when the option.title has a dash

- _includes/components/filters/isotope.html
Added I modify the file to filter points in the title.
> Add dot filters

- _includes/components/info-cards/card-deck.html
- _includes/components/jumbotron/bootstrap.html
- _includes/components/social-media/facebook.html
- _sass/components/info-cards/_card-deck.scss
- assets/css/main.min.scss
Also updated jumbotron component to extend all his height
Based on: 
https://github.com/twbs/bootstrap/issues/20321#issuecomment-368263733
> Create facebook & card-deck components

- _includes/components/firebase/ui.html
🐛 Fixes https://circleci.com/gh/cetinajero/grupopv.com.br/38
📝 More at: https://github.com/firebase/firebaseui-web/pull/544
> Update Portuguese (Brazilian) language code

- _includes/components/info-cards/search-results.html
- _includes/components/login/progressive.html
- _includes/components/product-cards/progressive.html
- _includes/components/sliders/bootstrap.html
- _includes/components/videos/youtube.html
- _sass/components/product-cards/_basic.scss
- assets/css/main.min.scss
> Avoid generic CSS, prefer spacing utility classes

- _includes/components/contact-cards/phone-card.html
- _includes/components/copyrights/progressive.html
- _includes/components/footers/progressive/footer.html
- _includes/components/logos/motorola.html
- _sass/components/contact-cards/_phone-card.scss
This PR creates a new logo component and use it on the customers footer
👋
> Create Motorola logo component

- _data/components/footers/progressive/common.yml
- _pages/footer/support/gift-cards/check-your-balance.md
- _pages/footer/support/gift-cards/email-gift-cards.md
- _pages/footer/support/gift-cards/gift-cards.md
- _pages/footer/support/gift-cards/mail-gift-card.md
- _pages/footer/support/marketing.md
- _pages/footer/support/search.md
- _pages/footer/support/sizes-lists.md
- _pages/footer/support/stores-all.html
- _pages/footer/support/videos.html
- _pages/footer/support/youtube.md
> Menu support section

- _includes/components/product-cards/product-generals.html
- _includes/components/product-cards/progressive.html
This PR makes posible to configure per collection if the prices are going to be showed.
The customization is created thru de config file.
✌️
> Disable prices per collection

- _includes/components/product-cards/product-generals.html
- _includes/components/product-cards/progressive.html
When a span has an HTML comment inside a liquid tag... it will generate 
an empty badge, this PR fix that.
✌️
> Fix empty badge prices

- _includes/components/panels/brands.html
- _sass/components/videos/background.scss
Also make the video background component more tall
✌️
> Create brands component

- _includes/components/sliders/bootstrap.html
> Fix issue when the slider doesn't have a title

- _includes/components/bullets/fontawesome.html
- _includes/components/cards/bootstrap-h.html
- _includes/components/cards/bootstrap-v.html
- _includes/components/product-cards/product-details.html
> Create bootstrap-(h|v) cards & fontawesome bullets components

- _includes/components/cards/bootstrap-v.html
Add text paragraph to bootstrap vertical card (as the horizontal one already have one)
> Update bootstrap-v component

- _includes/components/social-media/facebook.html
This allows you to be customized from the config
> The Facebook plugin component was modified

- _includes/components/stylesheets/progressive.html
> Comment unneeded CSS stylesheets

- _includes/components/stylesheets/progressive.html
- assets/vendors/revolution-slider/css/settings.css
- assets/vendors/themeforest/progressive/css/base.css
- assets/vendors/themeforest/progressive/css/buttons.css
- assets/vendors/themeforest/progressive/css/cms.css
- assets/vendors/themeforest/progressive/css/responsive.css
- assets/vendors/themeforest/progressive/css/social-icons.css
> Add themeforest and revolution-slider CSS code

- _includes/components/stylesheets/progressive.html
- assets/vendors/themeforest/progressive/css/animate.css
Co-authored-by: @mlopez-grupopv 
✌️
> Add animate.css to enable transition animatios @ landing page

- CHANGELOG.md
- Rakefile
- lib/jekyll_theme_marketing.rb
- lib/jekyll_theme_marketing/content.rb
- lib/jekyll_theme_marketing/deploy.rb
- lib/jekyll_theme_marketing/git.rb
This commit also creates the `Git` & `Content` Ruby modules.
✌️
> Create Deploy Gem task to publish new releases at rubygems.org

- _config.yml
- index.md
- jekyll-theme-marketing.gemspec
- lib/jekyll_theme_marketing/deploy.rb
- lib/jekyll_theme_marketing/git.rb
> Commit all release files into a single commit

- Gemfile.lock
- _includes/components/videos/background.html
- _sass/common/_common.scss
- _sass/components/videos/background.scss
- assets/vendors/themeforest/progressive/css/style.css
- index.md
Also updated the landing page and cleaned some old CSS code
This PR updates `bundler` to v2.1.0 to fix the CI issues found in the first commit:
More at: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
✌️
> Redesign the video background component

- Gemfile.lock
- _includes/components/panels/brands.html
- index.md
> add logos to brand panel

- _sass/components/jumbotron/bootstrap.scss
- index.md
> Center background image on jumbotron component

- _includes/components/chats/zendesk.liquid
- _includes/components/scripts/head.js
- _includes/components/zendesk/script.js
> Create zendesk chat component with widget option

- _includes/components/chats/zendesk.liquid
The CE419 customer reported the issue.
> 🐛 Fix old Zendesk chat plugin

- _includes/components/headings/bootstrap.liquid
- _layouts/page.html
- _shoes-man/shoes-man.md
- _shoes-woman/shoes-woman.md
Logo added with https://www.textgiraffe.com
✌️
> Create headings component

- .dependabot/config.yml
> Create Dependabot config file

- .rubocop.yml
- .travis.yml
- Gemfile
- Gemfile.lock
Also added `rake` as a dependency so `Gemfile`s are normalized thru all projects
✌️
> Bump ruby from 2.5.3 to 2.5.8

- _includes/components/product-cards/product-details.liquid
- _sass/components/product-cards/_product-details.scss
This PR ofuscantes the product's catalog images so we can minimize the attachment of them to emails.
This is easy to overcome but good enough to stop the casual user.
✌️
> Ofuscate a little the product's catalog images

- .dependabot/config.yml
- CODEOWNERS
> Add mlopez as a Ruby dependencies bump codeowner

- _includes/components/search-engines/lunr.js
> Temporary disable the search engine

- _includes/components/login/progressive.liquid
- lib/jekyll_theme_marketing/test.rb
A new option to visit links has been added to the monthly promotions login section.
> Added link option to promotions login

- _includes/components/product-cards/progressive.liquid
- _includes/components/ribbons/font-awesome.liquid
- _shoes-woman/high/565396F.md
- _shoes-woman/high/565396F2.md
- _shoes-woman/high/565396F3.md
- _shoes-woman/high/565396F4.md
- _shoes-woman/high/565396F5.md
This PR creates a ribbon component to be used on the current product card.
Note: Also included 4 products used as dummy to show the ribbon in action.
P.S. Thanks to @dtrevino-grupopv for the ribbon's responsive design! 🙌 
Screenshot:
✌️
> Create ribbon component

- _config.yml
- _includes/components/product-cards/progressive.liquid
- _shoes-man/high/565396F.md
- _shoes-man/low/564995c.md
- _shoes-woman/high/565396F3.md
This PR allows us to toggle off the ribbon component per:
---
Please note that the config in `config.yml` is now simplified and it reads easily than before! 🎉 
Example:
```yaml
components:
ribbon: disabled          # Disables the whole component
shoes-man: disabled     # Disables a whole collection
high-565396f3: disabled # Disables only a product
high-565396f4: disabled # Disables only a product
```
✌️
> Add on/off toogle for the ribbon component 

- _includes/components/product-cards/3d-space.liquid
This was needed to use this component card to other cases besides special offers
✌️
> Remove special-offers hash rule from 3d card

- Rakefile
- _config.yml
- _includes/components/product-cards/product-generals.liquid
- _includes/components/product-cards/progressive.liquid
- _shoes-woman/high/565396F5.md
This PR allows us to disable a price per product at the product's config.
This configuration will be valid for all customers and original sites.
---
Also:
- Documentation:
✌️
> Disable prices per product

- _includes/components/product-cards/progressive.liquid
- _shoes-woman/high/565396F.md
- _shoes-woman/high/565396F2.md
- _shoes-woman/high/565396F3.md
- _shoes-woman/high/565396F4.md
- _shoes-woman/high/565396F5.md
- _shoes-woman/high/high.md
> Add filters to desc with regex

- _includes/components/product-cards/progressive.liquid
✌️ 
Ref: https://github.com/grupopv/soporte-ti/issues/100
> Activate links on pages collection

- _config.yml
- _data/customers/carnival-bar.com.yml
- _data/customers/colifror-bri.com.jp.yml
- _data/customers/fleur.com.yml
- _includes/components/forms/formspree.js
- _includes/components/forms/formspree.liquid
Note: The next feature for the response page [is now a paid feature](https://help.formspree.io/hc/en-us/articles/360012378333--Thank-You-redirect).
Because of this, now the response page isn't showed anymore; We may need to update the submit function later to an AJAX request so we can enhance the form behavior but for now on, this fixes https://github.com/cetinajero/grupopv.mx/issues/357.
✌️
> Update formspree to the new endpoint

- _config.yml
- _includes/components/product-cards/featured-product.liquid
Ref: https://github.com/cetinajero/grupopv.mx/pull/369
✌️
> Featured product cards customizable per customer website

- _includes/components/headers/three-rows.liquid
- _includes/components/megamenu/progressive.liquid
- _sass/components/headers/_progressive.scss
- _sass/components/navbars/_progressive.scss
> Adjust hover nav colors to accommodate all style websites

- _data/menus/common.yaml
- _includes/components/nav-items/bootstrap.liquid
- _sass/components/nav-items/bootstrap.scss
Also added some dummy content
✌️
> Update colors for bootstrap navbar

- _includes/components/carousels/infinite.liquid
- _sass/components/carousels/_infinite.scss
- assets/css/main.min.scss
- index.md
Ref: https://codepen.io/studiojvla/pen/qVbQqW
✌️
> Create infinite carousel component for brands panel

- _includes/components/carousels/infinite.liquid
- _sass/components/carousels/_infinite.scss
- index.md
> Make the infinite carousel more configurable

- _includes/components/forms/formspree.liquid
> Only show the checkbox component on Grupo PV

- _config.yml
- _data/i18n/common/footer/en_US.yml
- _includes/components/videos/background.liquid
- _sass/components/videos/background.scss
- index.md
Also:
- Updated footer bottom **font color**, and
- Added dummy text.
✌🏼
> Move video background padding to component config

- _data/i18n/common/footer/en_US.yml
- _includes/components/copyrights/progressive.liquid
> Add privacy terms to copyrights component

- _includes/components/sliders/revolution-slider.liquid
> Add relative url filter to revolution slider's links

- _includes/components/assets/file-downloads.liquid
- _includes/components/carousels/slick.liquid
- _includes/components/product-cards/product-details.liquid
- _includes/components/videos/youtube.liquid
- _layouts/product.liquid
- _shoes-woman/high/565396F.md
> Rearrange design @ product page tabs

- _includes/components/megamenu/progressive.liquid
> Megamenu's image based on menu name rather than collection

- _sass/components/megamenu/_progressive.scss
- _sass/components/navbars/_progressive.scss
- assets/vendors/themeforest/progressive/css/base.css
- assets/vendors/themeforest/progressive/css/responsive.css
- assets/vendors/themeforest/progressive/css/style.css
Also deleted some old style rules.
✌🏼
> Renew megamenu design

- _includes/components/videos/background.liquid
- index.md
Now we won't get any broken links on video-backgrounds, they won't skip our CI tests.
✌🏼
> Add video-background links to html-proofer tests

- .travis.yml
- Gemfile
- Gemfile.lock
- _includes/components/info-cards/cart-summary.html
- _includes/components/nav-tabs/vertical-pills.liquid
- _includes/components/search-engines/lunr.liquid
- _includes/components/searchbars/progressive.liquid
- _includes/components/shopping-carts/vanilla-cart-js/cart.js
- jekyll-theme-marketing.gemspec
> Shopping cart (part three)

- _includes/components/copyrights/progressive.liquid
- _includes/components/footers/progressive/footer.liquid
- Delete Copyrights
- Delete img
> Motorola is removed in the footer

- _includes/components/panels/catalogs.liquid
- _pages/footer/grupopv/catalogs-and-brochures.md
> Add filter to catalogs to disable them per collection

- _includes/components/parallax/sections.liquid
- _sass/components/parallax/_sections.scss
- assets/css/main.min.scss
- index.md
> Parallax component

- _config.yml
- _includes/components/meta/progressive.liquid
> Customizable favicon

- _includes/components/assets/file-downloads.liquid
- _includes/components/breadcrumbs/bootstrap.liquid
> Don't capitalize data/i18n translations

- _config.yml
- _includes/components/chats/whatsapp.liquid
- _includes/components/scripts/head.js
- _sass/components/chats/_whatsapp.scss
- assets/css/main.min.scss
> Create Whatsapp chat component

- _config.yml
- _includes/components/info-cards/customers-intro.liquid
> Update components intro trigger

- _includes/components/search-engines/lunr.js
This fixes an issue when the search method didn't return results if it wasn't initialized.
✌🏼
> Optimize search engine

- _includes/components/cards/business-card.liquid
> Spacing on business card xs view

- _includes/components/product-cards/product-details.liquid
> Detect missing catalog spec sheets

- _includes/components/product-cards/featured-product.liquid
- _sass/components/product-cards/featured-product.scss
- index.md
- Added texts with links
- The card was modified to show logos at the top of the website
> Modifications in feature-product

- _includes/components/copyrights/copycat.js
> Add staging and LAN to copycat exceptions

- _includes/components/navbars/progressive.js
> Move spares urls to second collection

- _config.yml
- _includes/components/navbars/data/collections.liquid
> Define custom navbar links per website

- _includes/components/apps/downloads.js
- _includes/components/filters/isotope.js
- _layouts/grid.liquid
- _pages/footer/support/downloads-app.md
- _sass/components/apps/_downloads.scss
- assets/css/main.min.scss
> Create downloads app

- _data/components/footers/progressive/common.yml
- _includes/components/apps/downloads.js
- _includes/components/topbars/progressive.liquid
- _pages/footer/support/downloads-app.md
- _sass/components/apps/_downloads.scss
- assets/js/firebase/firebase-account-controller.js
- assets/js/firebase/firebase-special-offers.js
- index.md
Also make relative the firebase login urls
✌🏼
> Fix downloads app table style

- _includes/components/apps/downloads.js
> Add personal firebase items to downloads section

- _includes/components/cards/business-card.liquid
- _pages/footer/grupopv/catalogs-and-brochures.md
- _pages/footer/grupopv/events/events.md
- _pages/footer/grupopv/events/fix-to-ride-2016.liquid
> Make business card's company param customizable

- _includes/components/checks/always-https.js
- _includes/components/scripts/head.liquid
> Create always HTTPS component

- _includes/components/bullets/fontawesome.liquid
- _shoes-man/high/565396F.md
> Add sub specs to bullets component

- _includes/components/product-cards/product-generals.liquid
> Move promotional prices to a new line

- _includes/components/product-cards/product-generals.liquid
> Link to contact form

- _config.yml
- _includes/components/analytics/google-tag-manager/body.liquid
- _includes/components/analytics/google-tag-manager/head.liquid
- _includes/components/scripts/body.liquid
- _layouts/default.liquid
> Create google tag manager component
